### ISSUE TITLE
Kill the old leader?

### ISSUE THREAD

**Issue by kvaps** [LINBIT/k8s-await-election#2]
Nice project @WanzenBug! 🎉🎉

I just wanted to clarify about the possible situation of preserving the state of failed linstor-controller.

During failover the ingress traffic will expectedly be routed to another controller, this is fine.
But I'm worry about the first controller, will it be killed or continue working?

Imagine we are having kube-apiserver and three nodes: `node1`, `node2` `node3`:

- linstor controller deployed with three replicas on `node1`, `node2` `node3`
- current leader is  `node1`
- `node1` is loosing connectivity to the kube-apiserver
- new leader elected is `node2` all ingress traffic is rerouted to `node2`
- `node1` is back online

what will be happen?

**Comment by WanzenBug** [comment]
The controller is killed as soon as it cannot renew the lease. Which should be the same time the other nodes start the new election.

**Comment by kvaps** [comment]
Thanks, I will definitely a try!

**Comment by gecube** [comment]
Did not find this information in the README.md, but it is real game-changer. So we can equip non-cloud applications with this nice tool. It is very important to explicitly explain - what happens with the main process of app in case when losing the lease lock.
